---
language: python
services: docker

env:
  global:
    - ROLE_NAME: nginx
  matrix:
    - MOLECULE_DISTRO: centos7
    - MOLECULE_DISTRO: ubuntu1804
    - MOLECULE_DISTRO: debian9
    - MOLECULE_DISTRO: debian10

install:
  # Install test dependencies.
  - pip install molecule docker ansible-lint

before_script:
  # Use actual Ansible Galaxy role name for the project directory.
  - cd ../
  - mv ansible-nginx-base VerosK.$ROLE_NAME
  - cd VerosK.$ROLE_NAME

script:
  # Run tests.
  - molecule test

notifications:
  webhooks:
    - https://galaxy.ansible.com/api/v1/notifications/
