---
- name: Converge
  hosts: all

  vars_files:
    - vars/empty_site.yml

  pre_tasks:
    - name: Add gpg on Ubuntu 18.04
      apt:
        name: gpg
        install_recommends: false
        cache_valid_time: 3600
      when:
        - ansible_distribution == 'Ubuntu'
        - ansible_distribution_major_version|int >= 18

    - name: Add gpg on Debian
      apt:
        name: gpg
        install_recommends: false
        cache_valid_time: 3600
      when:
        - ansible_distribution == 'Debian'
        - ansible_distribution_major_version|int >= 9

  roles:
    - role: VerosK.acme-sh
